Relocatable Package: create product prefixed relocatable archive
scylladb/scylla-python3 pull request #11
Opened 2020-10-12 10:03 UTC by eliransin

The build system was hardcoded to produce a package that is
prefixed with scylla instead of the product name. This is not
in line with out CI system requirements and can be also a source
for confusion.
This commit make the packaging system generate a package of
the format: {product}-python3-package.tar.gz instead of
scylla-python3-package.tar.gz

2020-10-12 10:08 UTC, yaronkaikov commented
@eliransin I think you should change the reference to scylladb:next

2020-10-12 10:11 UTC, yaronkaikov commented
@eliransin I think `configure.py` also need to be modified. we should also do this change for jmx and tools, shouldn't we?

2020-10-12 10:14 UTC, eliransin commented
> @eliransin I think `configure.py` also need to be modified.

This is going to be the final step, configure.py is on the scylla repository, it can't be changed until we update all of the
submodules.

2020-10-12 10:17 UTC, yaronkaikov requested changes

2020-10-12 10:17 UTC, yaronkaikov commented on reloc/build_reloc.sh
> +VERSION=$(./SCYLLA-VERSION-GEN ${VERSION_OVERRIDE:+ --version "$VERSION_OVERRIDE"})
We don't have different repository for enterprise, so if you run SCYLLA-VERSION-GEN from pyhton3 submodule it will still generate `scylla` even if you run it under `scylla-enterprise`

Maybe we should run SCYLLA-VERSION-GEN from scylla-enterprise repo instead of the submodule?

2020-10-12 10:21 UTC, yaronkaikov commented
> > @eliransin I think `configure.py` also need to be modified.
> 
> This is going to be the final step, configure.py is on the scylla repository, it can't be changed until we update all of the
> submodules.

Yep, just saw you actually in the submodule repo

2020-10-12 11:05 UTC, eliransin commented on reloc/build_reloc.sh
> +VERSION=$(./SCYLLA-VERSION-GEN ${VERSION_OVERRIDE:+ --version "$VERSION_OVERRIDE"})
It will since I ampassing it the VERSION_OVERRIDE which looks something like:
scylla-enterprise-10-20 (product-version-release format). 
You can actually check that I am right with running on the original python3 module:
`./SCYLLA-VERSION-GEN --version scylla-enterprise-10-20` and examine the files generated in the `./build`
folder :slightly_smiling_face:

2020-10-12 11:12 UTC, yaronkaikov approved these changes

2020-10-13 06:53 UTC, eliransin commented
@penberg ping (merge or comment :slightly_smiling_face: )

2020-10-15 06:21 UTC, eliransin commented
@scylladb/scylla-tools-maint can someone merge please

2020-10-18 06:03 UTC, eliransin commented
@scylladb/scylla-tools-maint ping

2020-10-18 06:28 UTC, nyh approved these changes

2020-10-18 06:29 UTC, nyh commented
Committed, 1763a1a8348dac7d2d8e4930a5550ffec6537cf1

2020-10-18 06:29 UTC, closed without merging